### ISSUE TITLE
Package seems to be broken when using SPM on version 1.1.2

### ISSUE THREAD

**Issue by CassiusPacheco** [magiclabs/magic-ios-ext#8] opened 2023-03-07 06:32 UTC
Hi there,

I've noticed the package won't build in the latest version, due to a series issues. It appears that some inner dependencies require iOS 13+, whilst the package is set to 10+. Upon fixing that, other issues appear such as Magic_Web3 module not found and later that `MA_EXTENSION_ONLY_MSG` wasn't found.

What's weird is that I see that MagicSDK v7.0.0 is being downloaded as a dependency, but the code itself is not matching the one available under that tag, which causes it to fetch `Boilertalk/Web3.swift` under the hood, plus all the new missing code.

You can see that it appears to be easily reproducible by just trying to import it from a new project.

Let me know if there's anything else I can do to help fix that.
 
[MagicTest.zip](https://github.com/magiclabs/magic-ios-ext/files/10906122/MagicTest.zip)

**Comment by Ariflo** [comment] 2023-03-07 22:19
Thanks for bringing this to our attention @CassiusPacheco, we'll send up a fix asap.

**Comment by Ariflo** [comment] 2023-03-07 22:42
@CassiusPacheco from what I can tell you may actually just need to do a clean install to get passed these errors. Have you tried troubleshooting with our [demo iOS app](https://github.com/magiclabs/magic-ios-demo)? FWIW, I was unable to reproduce your errors with this [Simple iOS App](https://github.com/Ariflo/SimpleIOSMagicApp). LMK what you find.

**Comment by CassiusPacheco** [comment] 2023-03-07 22:53
@Ariflo what do you mean by clean install? I've cleaned the build folder + derived data multiple times before trying this. I'm on Xcode Version 14.2 (14C18).

Also, the SPM demo iOS app you linked doesn't seem to be correctly setup for SPM? There are no dependencies setup, so it won't fetch them. It seems like the project is relying directly on the Cocoapods dependencies, which is not what the SPM version is meant to do?

![Screenshot 2023-03-08 at 9 50 37 am](https://user-images.githubusercontent.com/662062/223572533-908544dd-cd5a-4827-8d4e-c04a0a2c25cb.png)

**Comment by Ariflo** [comment] 2023-03-07 23:10
@CassiusPacheco Apologies, as my Simple iOS App wasn't up-to-date. Try it again. Let me know if you still run into the error. 

> You should remove that, and add https://github.com/magiclabs/magic-ios-ext.git....

Not sure I follow, the `magic-ios-ext` requires that our main `magic-ios` package be installed.

**Comment by CassiusPacheco** [comment] 2023-03-07 23:27
@Ariflo 
> Not sure I follow, the magic-ios-ext requires that our main magic-ios package be installed.

sure, you can leave it directly set in there, doesn't matter because by depending on magic-ios-ext SPM will automatically fetch all of its dependencies, including magic.

Anyway, I've downloaded the new version of your Simple iOS App, and the problem is that you're not linking the Extension OIDC Library as I've mentioned before.

Have a look:
![Screenshot 2023-03-08 at 10 22 12 am](https://user-images.githubusercontent.com/662062/223578346-1c9e1fd6-5838-49d1-a6d2-52cec72eb642.png)

but they need to be linked, so I can import it and access the [openid property](https://github.com/magiclabs/magic-ios-ext/blob/main/Sources/MagicExt-OIDC/Core/OIDCExtension.swift#L22), which is the whole purpose of this package.

Once you link it, the problem appears.

![Screenshot 2023-03-08 at 10 26 57 am](https://user-images.githubusercontent.com/662062/223578617-40dd01d7-b562-4746-ae25-e9d0e11f05ef.png)

**Comment by Ariflo** [comment] 2023-03-08 01:27
Thank you again for your patience @CassiusPacheco, looks like dropping support for iOS v10 does the trick. We should have the ☝️ fix released tomorrow.

**Comment by CassiusPacheco** [comment] 2023-03-08 01:32
@Ariflo awesome, thanks. May I also suggest you set macOS to 10_15, since it's what the dependencies require: iOS 13 and macOS 10.15

**Comment by Ariflo** [comment] 2023-03-08 18:03
Resolved with [v8.0.0](https://github.com/magiclabs/magic-ios/releases/tag/8.0.0) and [v2.0.0](https://github.com/magiclabs/magic-ios-ext/releases/tag/2.0.0)

**Closed by Ariflo** 2023-03-08 18:03 UTC

**Comment by CassiusPacheco** [comment] 2023-03-08 22:07
Thanks @Ariflo, I'll give it a spin today.

**Comment by CassiusPacheco** [comment] 2023-03-08 23:06
Hey @Ariflo have you tried using the new versions in your [Sample app](https://github.com/Ariflo/SimpleIOSMagicApp)? 

There are still issues. The first I can see is that [magic-ios-ext still depends on version 7 of magic](https://github.com/magiclabs/magic-ios-ext/blob/main/Package.swift#L22). So this prevents me from depending on extension 2.0.0 and Magic 8.0.0 at the same time.

Could you please try to use the OIDC feature of the ext package in a sample SPM app yourself to check all the issues that are coming out of it?

Thanks

**Comment by Ariflo** [comment] 2023-03-09 01:37
@CassiusPacheco I am so sorry, this was a clear over sight on my part. I'll send an update now. 🤦

**Comment by CassiusPacheco** [comment] 2023-03-09 23:32
Hey @Ariflo, happy to report that [v2.0.1](https://github.com/magiclabs/magic-ios-ext/releases/tag/2.0.1) has fixed the issues. Thanks
